template: "regression/v1"
data:
  location: {{INGEST_DATA_LOCATION}}
  format: {{INGEST_DATA_FORMAT}}
  sql: SELECT * FROM delta.`{{INGEST_DATA_LOCATION}}`
data_scoring:
  location: {{INGEST_SCORING_DATA_LOCATION}}
  format: {{INGEST_SCORING_DATA_FORMAT}}
  sql: SELECT * FROM delta.`{{INGEST_SCORING_DATA_LOCATION}}`
target_col: "fare_amount"
steps:
  split:
    split_ratios: {{SPLIT_RATIOS}}
    post_split_method: steps.split.process_splits
  transform:
    transformer_method: steps.transform.transformer_fn
  train:
    using: estimator_spec
    estimator_method: steps.train.estimator_fn
  evaluate:
    validation_criteria:
      - metric: root_mean_squared_error
        threshold: 10
  register:
    model_name: "taxi_fare_regressor"
    allow_non_validated_model: false
  predict:
    output_location: {{SCORED_OUTPUT_DATA_LOCATION}}
    output_format: {{SCORED_OUTPUT_DATA_FORMAT}}
metrics:
  primary: "root_mean_squared_error"
